# 1. CONEXIÓN A POSTGRESQL (Base de datos local)
spring.datasource.url=jdbc:postgresql://localhost:5432/plataforma_tutores
spring.datasource.username=postgres
spring.datasource.password=admin

# 2. CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' compara tus futuras clases de Java con Postgres para que todo encaje sin borrar datos
spring.jpa.hibernate.ddl-auto=update
# Muestra en la consola inferior las consultas SQL reales que haga tu código
spring.jpa.show-sql=true