# 1. CONEXIÓN A POSTGRESQL (Base de datos local)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# 2. CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' compara tus futuras clases de Java con Postgres para que todo encaje sin borrar datos
spring.jpa.hibernate.ddl-auto=update
# Muestra en la consola inferior las consultas SQL reales que haga tu código
spring.jpa.show-sql=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=${PORT:8080}
cloudinary.cloud_name=qoemvahw
cloudinary.api_key=181394488217887
cloudinary.api_secret=Bh3FzaH1XA2nmxV1WyIbgwCeqlA